"""
run_biomechanics.py
===================
Full pipeline: MediaPipe extraction -> kinematics -> metadata merge -> dedup by event_id -> summary_stats.csv

Usage
-----
  python run_biomechanics.py "D:/clips" -o "D:/output" --meta dataset_manual.csv
  python run_biomechanics.py "D:/clips" -o "D:/output" --meta dataset_manual.csv --preview (to see the skeleton overlaid on the videos)

Input CSV (dataset_manual.csv): video_name, event_id, t0_frame, kick_foot, goal_zone, result, camera_angle, gk_guessed

After running build_clips_master.py, manually copy clips_master.csv
and biomechanics_dataset_complete.csv to 03_statistical_analysis/ and 04_models/
before running the scripts in those folders.
"""

import os, sys, argparse
import numpy as np
import pandas as pd
from pathlib import Path

from pose_extractor import PoseExtractor
from signal_filter  import SignalFilter
from kinematics     import compute_kinematics

VIDEO_EXT = {'.mp4', '.avi', '.mov', '.mkv', '.MP4', '.MOV'}

# -- Mappings --------------------------------------------------------

FOOT_MAP = {
    'Right': 'right', 'right': 'right',
    'Left':  'left',  'left':  'left',
}
RESULT_MAP = {
    0: 'goal',  '0': 'goal',
    1: 'saved', '1': 'saved',
    2: 'post',  '2': 'post',
    4: 'out',   '4': 'out',
}
ZONE_NAMES = {
    1: 'Top Left Corner',    2: 'Top Center',    3: 'Top Right Corner',
    4: 'Middle Left',        5: 'Center',        6: 'Middle Right',
    7: 'Bottom Left Corner', 8: 'Bottom Center', 9: 'Bottom Right Corner',
    'Out': 'Out',
}

BIO_METRICS = [                                            # metrics used in the summary_stats
    'kick_knee_angle', 'supp_knee_angle',
    'kick_ankle_angle', 'supp_ankle_angle', 'kick_hip_angle',
    'left_elbow_angle', 'right_elbow_angle',
    'kick_angular_vel', 'kick_angular_accel', 'kick_foot_speed_ms',
    'running_speed_kmh', 'trunk_inclination',
    'lateral_trunk_lean', 'torso_torsion_angle',
]


# -- Metadata ----------------------------------------------------------

def _load_metadata(meta_csv: str) -> pd.DataFrame:
    df = pd.read_csv(meta_csv)
    print(f"  Metadata: {len(df)} record(s) | columns: {list(df.columns)}")

    def _build_id(row):                                    # rebuilds clip_id from the metadata
        vname = Path(str(row.get('video_name', ''))).stem.strip()
        eid   = str(row.get('event_id', '')).strip()
        t0    = str(row.get('t0_frame', row.get('t0', ''))).split('.')[0].strip()
        return f"crop_{vname}__event_{eid}__t0_{t0}"

    df['clip_id']   = df.apply(_build_id, axis=1)
    df['foot_used'] = df.get('kick_foot', pd.Series()).map(FOOT_MAP)
    df['outcome']   = df.get('result',    pd.Series()).map(RESULT_MAP)

    if 'goal_zone' in df.columns and 'target_zone' not in df.columns:
        df = df.rename(columns={'goal_zone': 'target_zone'})

    df = df.drop(columns=[c for c in ('ball_x', 'ball_y') if c in df.columns])

    keep = ['clip_id', 'event_id', 'video_name', 'foot_used', 'outcome',            # camera_angle is not generated by 01_extraction - it has to be added
            'target_zone', 'camera_angle', 'gk_guessed']                            # manually to dataset_manual.csv when there are multiple cameras
    return df[[c for c in keep if c in df.columns]].copy()


# -- Process a single clip ---------------------------------------------

def _r(val, dec=4):                                        # rounds a float, returns None if NaN or Inf
    try:
        v = float(val)
        return None if (np.isnan(v) or np.isinf(v)) else round(v, dec)
    except Exception:
        return None


def process_clip(video_path, extractor, filt, foot_used=None):
    clip_id = Path(video_path).stem
    data    = extractor.process_video(video_path, clip_id)
    kps_c   = filt.process(data['keypoints'], data['visibility'])
    kin     = compute_kinematics(kps_c, data['fps'],
                                 visibility=data['visibility'],
                                 kicking_leg=foot_used)

    n   = len(data['timestamps'])
    sfx = _r(kin.get('support_foot_x'))                    # support-foot position, one scalar per clip
    sfy = _r(kin.get('support_foot_y'))                    # computed on the second-to-last frame, relative to the kicking foot at frame 0

    rows = []
    for t in range(n):
        rows.append({
            'clip_id'              : clip_id,
            'frame'                : t,
            'time_sec'             : round(float(data['timestamps'][t]), 4),
            'is_contact_frame'     : int(t == n - 1),      # frame 19 = T0
            'kicking_leg'          : kin['kicking_leg'],
            'kick_knee_angle'      : _r(kin['kick_knee_angle'][t]),
            'supp_knee_angle'      : _r(kin['supp_knee_angle'][t]),
            'kick_ankle_angle'     : _r(kin['kick_ankle_angle'][t]),
            'supp_ankle_angle'     : _r(kin['supp_ankle_angle'][t]),
            'kick_hip_angle'       : _r(kin['kick_hip_angle'][t]),
            'left_elbow_angle'     : _r(kin['left_elbow_angle'][t]),
            'right_elbow_angle'    : _r(kin['right_elbow_angle'][t]),
            'kick_hip_angular_vel'   : _r(kin['kick_hip_angular_vel'][t]),
            'kick_angular_vel'       : _r(kin['kick_angular_vel'][t]),
            'kick_ankle_angular_vel' : _r(kin['kick_ankle_angular_vel'][t]),
            'kick_angular_accel'     : _r(kin['kick_angular_accel'][t]),
            'kick_foot_speed_ms'   : _r(kin['kick_foot_speed_ms'][t]),
            'running_speed_kmh'    : _r(kin['running_speed_kmh'][t]),
            'trunk_inclination'    : _r(kin['trunk_inclination'][t]),
            'lateral_trunk_lean'   : _r(kin['lateral_trunk_lean'][t]),
            'torso_torsion_angle'  : _r(kin['torso_torsion_angle'][t]),
            'mean_visibility_score': _r(kin['mean_visibility_score'][t]),
            'support_foot_x'       : sfx,                  # same value across every frame of the clip
            'support_foot_y'       : sfy,
        })

    kin['clip_id']    = clip_id
    kin['timestamps'] = data['timestamps']
    return kin, pd.DataFrame(rows)


# -- Main pipeline -------------------------------------------------

def run(clips_dir, out_dir, meta_csv=None,
        model_complexity=2, show_preview=False):

    clips_dir = Path(clips_dir)
    out_dir   = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    videos = sorted([p for p in clips_dir.iterdir() if p.suffix in VIDEO_EXT])
    if not videos:
        print(f'[ERROR] No videos in: {clips_dir}'); sys.exit(1)
    print(f'\n{len(videos)} clip(s) -> {out_dir}')

    # Metadata
    meta         = None
    foot_by_clip = {}
    if meta_csv and Path(meta_csv).exists():
        meta = _load_metadata(meta_csv)
        foot_by_clip = dict(zip(meta['clip_id'], meta['foot_used'].fillna('').tolist()))
    elif meta_csv:
        print(f'[WARNING] CSV not found: {meta_csv}')

    filt      = SignalFilter(vis_threshold=0.25, window=3, poly=2)

    all_dfs, all_kins = [], []
    ok = fail = 0

    for i, vp in enumerate(videos, 1):
        extractor = PoseExtractor(model_complexity=model_complexity, show_preview=show_preview)
        foot_used = foot_by_clip.get(vp.stem) or None       # None -> auto-detected in compute_kinematics
        print(f'[{i}/{len(videos)}]  {vp.name}', end='  ', flush=True)
        try:
            kin, df = process_clip(str(vp), extractor, filt, foot_used)
            all_dfs.append(df); all_kins.append(kin)
            ok += 1; print('[OK]')
        except Exception as e:
            fail += 1; print(f'[ERROR] {e}')
        extractor.close()                                    # closes this clip's extractor before creating the next one

    print(f'\n{ok} OK  {fail} ERROR')
    if not all_dfs:
        print('No data.'); return

    # -- Merge metadata -------------------------------------------
    global_df = pd.concat(all_dfs, ignore_index=True)
    if meta is not None:
        global_df = global_df.merge(meta, on='clip_id', how='left')
        print(f'Merge: {len(global_df)} rows x {len(global_df.columns)} columns')

    # -- Dedup by event_id ---------------------------------
    # when the same penalty has two camera angles, keeps the clip with the best visibility
    if 'event_id' in global_df.columns:
        clip_vis = (global_df.groupby('clip_id')['mean_visibility_score']
                    .mean().reset_index()
                    .rename(columns={'mean_visibility_score': '_vis'}))
        clip_ev  = global_df[['clip_id','event_id']].drop_duplicates()
        info     = clip_ev.merge(clip_vis, on='clip_id')
        best_idx = info.groupby('event_id')['_vis'].idxmax()
        best     = set(info.loc[best_idx, 'clip_id'])
        n_before = global_df['clip_id'].nunique()
        global_df = global_df[global_df['clip_id'].isin(best)].copy()
        all_kins  = [k for k in all_kins if k['clip_id'] in best]
        print(f'Dedup: {n_before} -> {global_df["clip_id"].nunique()} clips')

    # -- Sort columns -------------------------------------------
    id_c   = ['clip_id','frame','time_sec','is_contact_frame']
    meta_c = [c for c in ['video_name','event_id','camera_angle',
                            'target_zone','gk_guessed','outcome','foot_used']
               if c in global_df.columns]
    bio_c  = [c for c in ['kicking_leg','kick_knee_angle','supp_knee_angle',
                           'kick_ankle_angle','supp_ankle_angle','kick_hip_angle',
                           'left_elbow_angle','right_elbow_angle','kick_angular_vel',
                           'kick_angular_accel','kick_foot_speed_ms','running_speed_kmh',
                           'trunk_inclination','lateral_trunk_lean','torso_torsion_angle',
                           'mean_visibility_score']
              if c in global_df.columns]
    rest   = [c for c in global_df.columns if c not in id_c + meta_c + bio_c]
    global_df = global_df[id_c + meta_c + bio_c + rest]

    # -- Full CSV (per frame) ----------------------------------
    csv_path = out_dir / 'biomechanics_dataset_complete.csv'
    global_df.to_csv(csv_path, index=False)
    print(f'[OK] {csv_path}')

    _export_proximal_distal(all_kins, global_df, out_dir)
    _export_summary(global_df, out_dir)

    print(f'\nDone! -> {out_dir}')
    print(f'Next step: python build_clips_master.py -d {out_dir}')


# -- Export analysis CSVs --------------------------------------

def _export_proximal_distal(all_kins, global_df, out_dir):
    """Per-clip CSV with the proximal-distal sequence analysis hip -> knee -> ankle."""
    meta_cols = [c for c in ['foot_used','outcome','target_zone','event_id']
                 if c in global_df.columns]
    clip_meta = (global_df[global_df['frame'] == 0]
                 [['clip_id'] + meta_cols].set_index('clip_id'))

    rows = []
    for kin in all_kins:
        cid = kin['clip_id']
        row = {'clip_id': cid}

        if cid in clip_meta.index:                         # clip metadata
            for c in meta_cols: row[c] = clip_meta.loc[cid, c]

        row['peak_hip_vel']   = _r(kin.get('peak_hip_vel'))
        row['peak_knee_vel']  = _r(kin.get('peak_knee_vel'))
        row['peak_ankle_vel'] = _r(kin.get('peak_ankle_vel'))

        row['peak_hip_frame']   = kin.get('peak_hip_frame')
        row['peak_knee_frame']  = kin.get('peak_knee_frame')
        row['peak_ankle_frame'] = kin.get('peak_ankle_frame')

        row['dt_hip_to_knee']   = _r(kin.get('dt_hip_to_knee'))   # positive = correct order
        row['dt_knee_to_ankle'] = _r(kin.get('dt_knee_to_ankle'))
        row['proximal_distal_valid'] = kin.get('proximal_distal_valid')

        # Energy-transfer ratio between joints
        hip_vel = kin.get('peak_hip_vel',  0) or 0
        kn_vel  = kin.get('peak_knee_vel', 0) or 0
        ank_vel = kin.get('peak_ankle_vel',0) or 0
        row['vel_ratio_hip_knee']   = _r(kn_vel  / hip_vel if hip_vel > 1 else None)
        row['vel_ratio_knee_ankle'] = _r(ank_vel / kn_vel  if kn_vel  > 1 else None)

        rows.append(row)

    df = pd.DataFrame(rows)
    if 'target_zone' in df.columns:
        df['zone_name'] = df['target_zone'].astype(str)

    path = Path(out_dir) / 'proximal_distal_sequence.csv'
    df.to_csv(path, index=False)
    print(f'[OK] {path}  ({len(df)} clips)')


def _export_summary(df, out_dir):
    """Mean and standard deviation of the metrics at the contact frame, grouped by foot/zone/outcome."""
    contact  = df[df['is_contact_frame'] == 1].copy()
    present  = [m for m in BIO_METRICS if m in contact.columns]
    grp_cols = [c for c in ['foot_used','target_zone','outcome'] if c in contact.columns]
    if not grp_cols or not present: return

    if 'target_zone' in contact.columns:
        contact['target_zone'] = contact['target_zone'].map(lambda z: ZONE_NAMES.get(z, str(z)))

    summary = contact.groupby(grp_cols)[present].agg(['mean','std']).round(3)
    summary.columns = ['_'.join(c) for c in summary.columns]
    summary = summary.reset_index()

    path = Path(out_dir) / 'summary_stats.csv'
    summary.to_csv(path, index=False)
    print(f'[OK] {path}  ({len(summary)} group(s))')


# -- CLI -----------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(
        description='Biomechanical analysis of penalty kicks with MediaPipe.',
        formatter_class=argparse.RawDescriptionHelpFormatter, epilog=__doc__)
    ap.add_argument('clips_dir')
    ap.add_argument('--output', '-o', default=None)
    ap.add_argument('--meta',   '-m', default=None, help='Path to dataset_manual.csv')
    ap.add_argument('--model-complexity', type=int, default=2, choices=[0,1,2])
    ap.add_argument('--preview', action='store_true')
    args = ap.parse_args()

    run(clips_dir        = args.clips_dir,
        out_dir          = args.output or os.path.join(args.clips_dir, 'biomechanics'),
        meta_csv         = args.meta,
        model_complexity = args.model_complexity,
        show_preview     = args.preview)


if __name__ == '__main__':
    main()
